### ISSUE TITLE
éditeur manquant

### ISSUE THREAD

**Issue by alexbartz** [Antonomaz/Corpus#9]
https://github.com/Antonomaz/Corpus/blob/e2369829cb834b6895892aebd4124a1eb331a801/Mazarinades/3001-3100/M3030_GBOOKS.xml#L41

isni indiqué mais le `persName` n'est pas rempli
@CamLyon2 @Mechalilene

**Comment by CamLyon2** [comment]
<persName> rempli.

**Comment by CamLyon2** [comment]
persName rempli
